// Armada Public Adjusting intake automation.
//
// Given the fields Claude read off an intake photo (see llm.extractIntakeFields),
// this module fills the two Word templates (Welcome Letter + Notice to Insurance)
// and emails the filled documents to the firm via Resend.
//
// Templates live in ./templates as token-merged copies of the firm's originals
// (built by templates/build-templates.mjs). The boilerplate is untouched — only
// the blanks (Insured, Policy #, Claim #, Date of Loss, Loss Address, Cause of
// Loss, and the "Dear ___," salutation) carry {tokens}.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import PizZip from 'pizzip';
import Docxtemplater from 'docxtemplater';
import { Resend } from 'resend';
import type { IntakeFields } from './types.js';

export interface FilledDoc {
  filename: string;
  content: Buffer;
}

export interface EmailResult {
  sent: boolean;
  to: string;
  toShort: string;
  id?: string;
  reason?: string;
}

const TEMPLATE_DIR = fileURLToPath(new URL('./templates', import.meta.url));

function renderDocx(templateFile: string, data: Record<string, string>): Buffer {
  const zip = new PizZip(readFileSync(join(TEMPLATE_DIR, templateFile)));
  const doc = new Docxtemplater(zip, {
    paragraphLoop: true,
    linebreaks: true,
    nullGetter: () => '', // a missing token renders as blank, never "undefined"
  });
  doc.render(data);
  return doc.getZip().generate({ type: 'nodebuffer' });
}

/** Map the extracted fields onto the {tokens} the templates expect. */
function templateData(f: IntakeFields): Record<string, string> {
  const salutation = (f.insured_name.split(/\s+/)[0] || 'Valued Client').trim();
  return {
    insured: f.insured_name,
    salutation,
    policy_number: f.policy_number,
    claim_number: f.claim_number,
    date_of_loss: f.date_of_loss,
    loss_address: f.loss_address,
    cause_of_loss: f.cause_of_loss,
  };
}

function fileSlug(f: IntakeFields): string {
  const base = f.insured_name || f.claim_number || 'intake';
  return base.replace(/[^\w.\- ]+/g, '').trim().slice(0, 60) || 'intake';
}

/** Fill both templates. Pure/synchronous — no API or network involved. */
export function fillTemplates(f: IntakeFields): FilledDoc[] {
  const data = templateData(f);
  const slug = fileSlug(f);
  return [
    { filename: `Welcome Letter - ${slug}.docx`, content: renderDocx('welcome-letter.docx', data) },
    { filename: `Notice to Insurance - ${slug}.docx`, content: renderDocx('notice-to-insurance.docx', data) },
  ];
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function summaryHtml(f: IntakeFields): string {
  const rows: Array<[string, string]> = [
    ['Insured', f.insured_name],
    ['Loss Address', f.loss_address],
    ['Carrier', f.carrier],
    ['Policy #', f.policy_number],
    ['Claim #', f.claim_number],
    ['Date of Loss', f.date_of_loss],
    ['Cause of Loss', f.cause_of_loss],
    ['Phone', f.phone],
    ['Email', f.email],
  ];
  const body = rows
    .map(
      ([k, v]) =>
        `<tr><td style="padding:4px 12px 4px 0;color:#555;white-space:nowrap">${esc(k)}</td><td style="padding:4px 0;font-weight:600">${esc(v) || '<span style="color:#bbb;font-weight:400">— not on form —</span>'}</td></tr>`,
    )
    .join('');
  return `
    <div style="font-family:Segoe UI,Arial,sans-serif;color:#1f1a13">
      <p>A new intake was processed automatically. The drafted <strong>Welcome Letter</strong> and
      <strong>Notice to Insurance Company</strong> are attached as Word documents for review before sending.</p>
      <table style="border-collapse:collapse;font-size:14px">${body}</table>
      <p style="color:#888;font-size:12px;margin-top:18px">Generated by Agent World · Tessa the intake agent. Verify the extracted fields against the original form before forwarding.</p>
    </div>`;
}

function shortName(email: string): string {
  const addr = email.replace(/.*</, '').replace(/>.*/, '').trim();
  return addr.split('@')[0] || addr || email;
}

/** Email the filled documents to the firm. No-ops gracefully (sent:false) when
 *  RESEND_API_KEY is unset, so local runs draft documents without sending mail. */
export async function emailIntake(f: IntakeFields, docs: FilledDoc[]): Promise<EmailResult> {
  const to = process.env.INTAKE_TO_EMAIL?.trim() || 'Sele@armadapa.com';
  const from = process.env.INTAKE_FROM_EMAIL?.trim() || 'Armada Intake <claims@armadapa.com>';
  const toShort = shortName(to);
  const subject = `New Intake: ${f.insured_name || 'Unknown insured'}${f.claim_number ? ` — Claim ${f.claim_number}` : ''}`;

  const apiKey = process.env.RESEND_API_KEY?.trim();
  if (!apiKey) {
    return { sent: false, to, toShort, reason: 'RESEND_API_KEY not set — documents drafted but not emailed.' };
  }

  try {
    const resend = new Resend(apiKey);
    const { data, error } = await resend.emails.send({
      from,
      to: [to],
      subject,
      html: summaryHtml(f),
      attachments: docs.map((d) => ({ filename: d.filename, content: d.content })),
    });
    if (error) return { sent: false, to, toShort, reason: error.message || String(error) };
    return { sent: true, to, toShort, id: data?.id };
  } catch (err) {
    return { sent: false, to, toShort, reason: (err as Error).message };
  }
}
